applications:
  myapp:
    type: php:8.5
    source:
      root: "/"
    web:
      locations:
        "/":
          root: "/"
          passthru: "/index.php"
          index:
              - "index.php"
