name: 🧪 Test

on:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Fake secret injection
        env:
          FAKE_SECRET: "FAKE-12345-NOT-A-REAL-SECRET"
        run: |
          echo "Simulating secret usage..."
          echo "FAKE_SECRET is: $FAKE_SECRET"
