name: 🧪 Test

on:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Fake secret injection
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
          KEY_POP: ${{ secrets.KEY_POP }}
        run: bash run.sh

